# Generated by Django 4.2.7 on 2023-11-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('database', models.CharField(max_length=200)),
                ('mode', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('pgbouncer_pid', models.IntegerField(null=True)),
            ],
        ),
    ]
